on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.tinosnegocios.com.br
          username: rodolfo@tinosnegocios.com.br
          password: ${{ SECRETS.FTP_PASS || github.token }}
          server-dir: public_html/financas/